services:
  xray-node:
    build: .
    container_name: sfkt_xray_node
    restart: unless-stopped
    network_mode: host
    volumes:
      - xray-config:/etc/xray
      - ./logs:/var/log/xray
    env_file:
      - .env
    cap_add:
      - NET_ADMIN

volumes:
  xray-config:
