version: '3.8'

services:
  xray-node:
    build: .
    container_name: sfkt_xray_node
    restart: unless-stopped
    ports:
      - "443:443"
    volumes:
      - ./config:/etc/xray
      - ./logs:/var/log/xray
    environment:
      # Node identification
      - NODE_ID=${NODE_ID:-}
      - NODE_NAME=${NODE_NAME:-SFKT Node}
      - NODE_HOSTNAME=${NODE_HOSTNAME:-example.com}
      - NODE_IP=${NODE_IP:-0.0.0.0}
      - NODE_PORT=${NODE_PORT:-443}

      # Location
      - NODE_COUNTRY=${NODE_COUNTRY:-Russia}
      - NODE_COUNTRY_CODE=${NODE_COUNTRY_CODE:-RU}
      - NODE_CITY=${NODE_CITY:-Moscow}

      # REALITY keys
      - REALITY_PRIVATE_KEY=${REALITY_PRIVATE_KEY}
      - REALITY_PUBLIC_KEY=${REALITY_PUBLIC_KEY}
      - REALITY_SHORT_ID=${REALITY_SHORT_ID}

      # SNI
      - NODE_SNI=${NODE_SNI:-vk.com}

      # Main server connection
      - MAIN_SERVER_URL=${MAIN_SERVER_URL:-http://backend:8000}
      - NODE_API_KEY=${NODE_API_KEY}

      # Sync intervals
      - SYNC_INTERVAL=${SYNC_INTERVAL:-30}
      - HEALTH_CHECK_INTERVAL=${HEALTH_CHECK_INTERVAL:-60}
    networks:
      - sfkt_network
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.ip_forward=1

networks:
  sfkt_network:
    external: true
