services:
  xray-node:
    build: .
    container_name: sfkt_xray_node
    restart: unless-stopped
    ports:
      - "443:443"
    volumes:
      - xray-config:/etc/xray
      - ./logs:/var/log/xray
    env_file:
      - .env
    networks:
      - sfkt_network
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.ip_forward=1

volumes:
  xray-config:

networks:
  sfkt_network:
    external: true
